Robustness fixes.
In particular, do not fire up a program outside of the AppImage's /usr/bin. Cf. #464.

diff --git a/tools/AppRun b/tools/AppRun
--- a/tools/AppRun
+++ b/tools/AppRun
@@ -14,8 +14,8 @@ export PERLLIB="${APP_ROOT}/usr/share/perl5/:${APP_ROOT}/usr/lib/perl5/${PERLLIB
 export GSETTINGS_SCHEMA_DIR="${APP_ROOT}/usr/share/glib-2.0/schemas/${GSETTINGS_SCHEMA_DIR:+:$GSETTINGS_SCHEMA_DIR}"
 export QT_PLUGIN_PATH="${APP_ROOT}/usr/lib/qt4/plugins/:${APP_ROOT}/usr/lib/i386-linux-gnu/qt4/plugins/:${APP_ROOT}/usr/lib/x86_64-linux-gnu/qt4/plugins/:${APP_ROOT}/usr/lib32/qt4/plugins/:${APP_ROOT}/usr/lib64/qt4/plugins/:${APP_ROOT}/usr/lib/qt5/plugins/:${APP_ROOT}/usr/lib/i386-linux-gnu/qt5/plugins/:${APP_ROOT}/usr/lib/x86_64-linux-gnu/qt5/plugins/:${APP_ROOT}/usr/lib32/qt5/plugins/:${APP_ROOT}/usr/lib64/qt5/plugins/${QT_PLUGIN_PATH:+:$QT_PLUGIN_PATH}"
 
-if [ ! -z $APPIMAGE ] ; then
-    PROG_NAME=$(basename "$ARGV0")
+if [ ! -z "${APPIMAGE}" ] ; then
+    PROG_NAME=$(basename "${ARGV0}")
 else
     PROG_NAME=$(basename "$0")
 fi
@@ -25,9 +25,14 @@ fi
 case ${PROG_NAME} in
     *AppImage)
         EXEC=$(grep -e '^Exec=.*' "${APP_ROOT}"/*.desktop | head -n 1 | cut -d "=" -f 2 | cut -d " " -f 1)
-        exec "${EXEC}" "$@"
+        exec "${APP_ROOT}/usr/bin/${EXEC}" "$@"
+        ;;
+    irscrutinizer|irptransmogrifier)
+        exec "${APP_ROOT}/usr/bin/${PROG_NAME}" "$@"
         ;;
     *)
-        exec "${PROG_NAME}" "$@"
+        # No other names supported
+	echo "Invalid name \"${PROG_NAME}\", quitting"
+	exit 1
         ;;
 esac
